version: 2

sources:
  - name: erp
    description: fonte SAP de vendas da Adventure Works
    schema: sap_adw
    tables:
    - name: person
      description: tabela contendo informações de pessoas.
      columns:
        - name: businessentityid
          description: chave primária
          tests:
            - unique
            - not_null
    - name: customer
      description: tabela contendo informações de clientes.
    - name: salesreason
      description: tabela contendo informações de motivos de vendas.
      columns:
        - name: salesreasonid
          description: chave primária
          tests:
            - unique
            - not_null  
    - name: salesorderheader
      description: tabela contendo informações de pedidos de vendas. 
      columns:
        - name: salesorderid
          description: chave primária
          tests:
            - unique
            - not_null        
    - name: salesorderdetail
      description: tabela contendo informações de detalhes de vendas.
    - name: salesorderheadersalesreason
      description: tabela contendo informações para unir pedidos e detalhes dos pedidos.
    - name: product
      description: tabela contendo informações de produtos.
      columns:
        - name: productid
          description: chave primária
          tests:
            - unique
            - not_null  
    - name: address
      description: tabela contendo informações de detalhes de endereços.  
    - name: stateprovince
      description: tabela contendo informações de estados.
      columns:
        - name: stateprovinceid
          description: chave primária
          tests:
            - unique
            - not_null  
    - name: countryregion
      description: tabela contendo informações de detalhes de países.
      columns:
        - name: countryregioncode
          description: chave primária
          tests:
            - unique
            - not_null  